In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [ ]:
data = pd.read_csv('Churn_Modelling.csv')
data.head() 
#estimated salary is the output feature here. 
#  We will try to predict the estimated salary of a customer based on the other features.
# so this is regression problem.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Preprocess the data.

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
data.isnull().sum()  # no missing values in the dataset.

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
dtype: int64

### Encode categorical feature:

In [5]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

### One hot encoder for 'Geography' column:

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [7]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

### Combine onehot encoded column with original data:

In [8]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

### Split the data into dependant and independant features:

In [10]:
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [12]:
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0

In [13]:
y.head()

0    101348.88
1    112542.58
2    113931.57
3     93826.63
4     79084.10
Name: EstimatedSalary, dtype: float64

### Train test split:

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Save the encoders and scaler for later use:

In [16]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### Train ANN with problem statement:

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

### Build the model:

In [18]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [21]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 7ms/step - loss: 100368.1250 - mae: 100368.1250 - val_loss: 98482.8594 - val_mae: 98482.8594
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 99523.7188 - mae: 99523.7188 - val_loss: 96789.1094 - val_mae: 96789.1094
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 96613.9453 - mae: 96613.9453 - val_loss: 92539.6875 - val_mae: 92539.6875
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 90984.3203 - mae: 90984.3203 - val_loss: 85621.6016 - val_mae: 85621.6016
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 83002.5547 - mae: 83002.5547 - val_loss: 76935.1562 - val_mae: 76935.1562
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 73841.4062 - mae: 73841.4062 - val_loss: 68199.0859 - val_mae: 68199.0859
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 65295.2109 - mae: 65295.2109 - val_loss: 61053.1367 - val_mae: 61053.1367
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 58798.1758 - mae: 58798.1758 - val_loss: 56114.7188 - val_mae: 56114.7188
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 54709.1250 - mae: 54709.1250 - val_loss: 53403.6562 - val_mae: 53403.6562
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 52485.9883 - mae: 52485.9883 - val_loss: 52080.4883 - val_mae: 52080.4883
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 51400.8867 - mae: 51400.8867 - val_loss: 51479.1406 - val_mae: 51479.1406
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50882.1211 - mae: 50882.1211 - val_loss: 51224.9531 - val_mae: 51224.9531
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 50619.5000 - mae: 50619.5000 - val_loss: 51076.4688 - val_mae: 51076.4688
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 50464.8008 - mae: 50464.8008 - val_loss: 50975.6289 - val_mae: 50975.6289
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50359.7266 - mae: 50359.7266 - val_loss: 50896.3555 - val_mae: 50896.3555
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 50273.8008 - mae: 50273.8008 - val_loss: 50821.0703 - val_mae: 50821.0703
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 50202.4922 - mae: 50202.4922 - val_loss: 50769.1602 - val_mae: 50769.1602
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 50142.5352 - mae: 50142.5352 - val_loss: 50719.5430 - val_mae: 50719.5430
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 50093.0547 - mae: 50093.0547 - val_loss: 50665.9453 - val_mae: 50665.9453
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 50044.7461 - mae: 50044.7461 - val_loss: 50630.0781 - val_mae: 50630.0781
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 50007.8555 - mae: 50007.8555 - val_loss: 50598.1172 - val_mae: 50598.1172
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 49972.2578 - mae: 49972.2578 - val_loss: 50574.5625 - val_mae: 50574.5625
Epoch 23/100
250/250 [==============================] - 1s 4ms/step - loss: 49940.4688 - mae: 49940.4688 - val_loss: 50536.1680 - val_mae: 50536.1680
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 49909.2305 - mae: 49909.2305 - val_loss: 50507.5547 - val_mae: 50507.5547
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 49880.8867 - mae: 49880.8867 - val_loss: 50483.5352 - val_mae: 50483.5352
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49856.0391 - mae: 49856.0391 - val_loss: 50469.0430 - val_mae: 50469.0430
Epoch 27/100
250/250 [==============================] - 1s 4ms/step - loss: 49835.6953 - mae: 49835.6953 - val_loss: 50446.5703 - val_mae: 50446.5703
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 49812.3555 - mae: 49812.3555 - val_loss: 50433.8516 - val_mae: 50433.8516
Epoch 29/100
250/250 [==============================] - 1s 4ms/step - loss: 49788.8672 - mae: 49788.8672 - val_loss: 50417.3281 - val_mae: 50417.3281
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 49770.6055 - mae: 49770.6055 - val_loss: 50404.6328 - val_mae: 50404.6328
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 49749.4492 - mae: 49749.4492 - val_loss: 50387.0664 - val_mae: 50387.0664
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49729.5664 - mae: 49729.5664 - val_loss: 50376.6641 - val_mae: 50376.6641
Epoch 33/100
250/250 [==============================] - 1s 4ms/step - loss: 49717.2578 - mae: 49717.2578 - val_loss: 50365.9922 - val_mae: 50365.9922
Epoch 34/100
250/250 [==============================] - 1s 4ms/step - loss: 49697.1836 - mae: 49697.1836 - val_loss: 50352.8828 - val_mae: 50352.8828
Epoch 35/100
250/250 [==============================] - 1s 5ms/step - loss: 49681.9414 - mae: 49681.9414 - val_loss: 50352.9297 - val_mae: 50352.9297
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49665.6602 - mae: 49665.6602 - val_loss: 50346.9375 - val_mae: 50346.9375
Epoch 37/100
250/250 [==============================] - 1s 4ms/step - loss: 49652.9375 - mae: 49652.9375 - val_loss: 50348.8047 - val_mae: 50348.8047
Epoch 38/100
250/250 [==============================] - 1s 4ms/step - loss: 49640.2344 - mae: 49640.2344 - val_loss: 50343.5234 - val_mae: 50343.5234
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49625.8906 - mae: 49625.8906 - val_loss: 50345.9766 - val_mae: 50345.9766
Epoch 40/100
250/250 [==============================] - 1s 4ms/step - loss: 49613.5703 - mae: 49613.5703 - val_loss: 50340.5938 - val_mae: 50340.5938
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49602.8789 - mae: 49602.8789 - val_loss: 50325.5000 - val_mae: 50325.5000
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 49592.8008 - mae: 49592.8008 - val_loss: 50326.0039 - val_mae: 50326.0039
Epoch 43/100
250/250 [==============================] - 1s 4ms/step - loss: 49584.3555 - mae: 49584.3555 - val_loss: 50332.8750 - val_mae: 50332.8750
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49570.8516 - mae: 49570.8516 - val_loss: 50321.8086 - val_mae: 50321.8086
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 49563.6211 - mae: 49563.6211 - val_loss: 50318.2148 - val_mae: 50318.2148
Epoch 46/100
250/250 [==============================] - 1s 4ms/step - loss: 49555.1680 - mae: 49555.1680 - val_loss: 50331.1250 - val_mae: 50331.1250
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49548.0312 - mae: 49548.0312 - val_loss: 50314.9688 - val_mae: 50314.9688
Epoch 48/100
250/250 [==============================] - 1s 4ms/step - loss: 49537.4961 - mae: 49537.4961 - val_loss: 50304.0352 - val_mae: 50304.0352
Epoch 49/100
250/250 [==============================] - 1s 4ms/step - loss: 49534.2852 - mae: 49534.2852 - val_loss: 50303.1680 - val_mae: 50303.1680
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49523.5977 - mae: 49523.5977 - val_loss: 50299.1641 - val_mae: 50299.1641
Epoch 51/100
250/250 [==============================] - 1s 4ms/step - loss: 49514.0352 - mae: 49514.0352 - val_loss: 50308.0508 - val_mae: 50308.0508
Epoch 52/100
250/250 [==============================] - 1s 5ms/step - loss: 49508.8047 - mae: 49508.8047 - val_loss: 50316.9570 - val_mae: 50316.9570
Epoch 53/100
250/250 [==============================] - 1s 6ms/step - loss: 49504.6484 - mae: 49504.6484 - val_loss: 50311.5781 - val_mae: 50311.5781
Epoch 54/100
250/250 [==============================] - 2s 7ms/step - loss: 49499.4922 - mae: 49499.4922 - val_loss: 50306.9688 - val_mae: 50306.9688
Epoch 55/100
250/250 [==============================] - 1s 6ms/step - loss: 49491.3242 - mae: 49491.3242 - val_loss: 50293.8086 - val_mae: 50293.8086
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 49485.8125 - mae: 49485.8125 - val_loss: 50302.1602 - val_mae: 50302.1602
Epoch 57/100
250/250 [==============================] - 1s 5ms/step - loss: 49479.5742 - mae: 49479.5742 - val_loss: 50290.2148 - val_mae: 50290.2148
Epoch 58/100
250/250 [==============================] - 3s 10ms/step - loss: 49476.1094 - mae: 49476.1094 - val_loss: 50296.3086 - val_mae: 50296.3086
Epoch 59/100
250/250 [==============================] - 2s 9ms/step - loss: 49469.5000 - mae: 49469.5000 - val_loss: 50296.6094 - val_mae: 50296.6094
Epoch 60/100
250/250 [==============================] - 2s 7ms/step - loss: 49462.9336 - mae: 49462.9336 - val_loss: 50294.7930 - val_mae: 50294.7930
Epoch 61/100
250/250 [==============================] - 1s 5ms/step - loss: 49458.3867 - mae: 49458.3867 - val_loss: 50287.4453 - val_mae: 50287.4453
Epoch 62/100
250/250 [==============================] - 1s 5ms/step - loss: 49452.6250 - mae: 49452.6250 - val_loss: 50306.4570 - val_mae: 50306.4570
Epoch 63/100
250/250 [==============================] - 1s 5ms/step - loss: 49451.0625 - mae: 49451.0625 - val_loss: 50296.0859 - val_mae: 50296.0859
Epoch 64/100
250/250 [==============================] - 1s 4ms/step - loss: 49448.0234 - mae: 49448.0234 - val_loss: 50294.9375 - val_mae: 50294.9375
Epoch 65/100
250/250 [==============================] - 1s 5ms/step - loss: 49439.6641 - mae: 49439.6641 - val_loss: 50294.9141 - val_mae: 50294.9141
Epoch 66/100
250/250 [==============================] - 1s 5ms/step - loss: 49435.3672 - mae: 49435.3672 - val_loss: 50287.9219 - val_mae: 50287.9219
Epoch 67/100
250/250 [==============================] - 1s 5ms/step - loss: 49428.6836 - mae: 49428.6836 - val_loss: 50280.0078 - val_mae: 50280.0078
Epoch 68/100
250/250 [==============================] - 1s 4ms/step - loss: 49425.8906 - mae: 49425.8906 - val_loss: 50284.9570 - val_mae: 50284.9570
Epoch 69/100
250/250 [==============================] - 1s 4ms/step - loss: 49423.2852 - mae: 49423.2852 - val_loss: 50308.9062 - val_mae: 50308.9062
Epoch 70/100
250/250 [==============================] - 1s 4ms/step - loss: 49419.3945 - mae: 49419.3945 - val_loss: 50304.4961 - val_mae: 50304.4961
Epoch 71/100
250/250 [==============================] - 1s 4ms/step - loss: 49414.2617 - mae: 49414.2617 - val_loss: 50301.3906 - val_mae: 50301.3906
Epoch 72/100
250/250 [==============================] - 1s 4ms/step - loss: 49413.7344 - mae: 49413.7344 - val_loss: 50307.4062 - val_mae: 50307.4062
Epoch 73/100
250/250 [==============================] - 1s 4ms/step - loss: 49405.7773 - mae: 49405.7773 - val_loss: 50297.5547 - val_mae: 50297.5547
Epoch 74/100
250/250 [==============================] - 1s 5ms/step - loss: 49404.6836 - mae: 49404.6836 - val_loss: 50302.8008 - val_mae: 50302.8008
Epoch 75/100
250/250 [==============================] - 1s 6ms/step - loss: 49398.2070 - mae: 49398.2070 - val_loss: 50302.3008 - val_mae: 50302.3008
Epoch 76/100
250/250 [==============================] - 1s 4ms/step - loss: 49396.0586 - mae: 49396.0586 - val_loss: 50301.8125 - val_mae: 50301.8125
Epoch 77/100
250/250 [==============================] - 1s 5ms/step - loss: 49391.2617 - mae: 49391.2617 - val_loss: 50288.7656 - val_mae: 50288.7656

In [22]:
%load_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/

Reusing TensorBoard on port 6007 (pid 6024), started 0:01:00 ago. (Use '!kill 6024' to kill it.)

In [26]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 5ms/step - loss: 50280.0078 - mae: 50280.0078
Test MAE : 50280.0078125

In [27]:
model.save('regression_model.h5')

d:\2. Course\11 EndToEndMLProject\5 ChurnModellingANN\churnvenv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(